-- AlterTable
ALTER TABLE `Order` ADD COLUMN `status` ENUM('INFO_RECIEVED', 'PENDING', 'IN_TRANSIT', 'DELIVERED', 'RETURNED', 'EXCEPTION', 'FAIL_ATTEMPT') NOT NULL DEFAULT 'INFO_RECIEVED',
    MODIFY `awb` VARCHAR(191) NULL,
    MODIFY `jrn` VARCHAR(191) NULL;
